add_newline = true

format = """
$username$hostname $directory $time
$character"""

[username]
show_always = true
format = "[ $user](bold #ff2748)"

[hostname]
ssh_only = false
format = "[@$hostname](bold #8fa8ff)"

[directory]
home_symbol = "~"
truncation_length = 1
format = "[ $path](bold #dce7ff)"

[git_branch]
symbol = " "
format = "[ $symbol$branch](bold #b58ae6)"

[time]
disabled = false
time_format = "%H:%M"
format = "[󰥔 $time](bold #dce7ff)"

[character]
success_symbol = "[╰─❯](bold #ff2748)"
error_symbol = "[╰─❯](bold #8fa8ff)"

[git_status]
disabled = true
