# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=#050203

# Main text color
theme[main_fg]=#f8e0e1

# Title color for boxes
theme[title]=#f8e0e1

# Highlight color for keyboard shortcuts
theme[hi_fg]=#f6b6bd

# Background color of selected item in processes box
theme[selected_bg]=#0b0506

# Foreground color of selected item in processes box
theme[selected_fg]=#f6b6bd

# Color of inactive/disabled text
theme[inactive_fg]=#837172

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]=#ffdff9

# Background color of the percentage meters
theme[meter_bg]=#837172

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]=#ffdff9

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]=#ffa6c5
theme[mem_box]=#ffd8c5
theme[net_box]=#f7aab4
theme[proc_box]=#fca1d1

# Box divider line and small boxes line color
theme[div_line]=#544445

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]=#ffd8c5
theme[temp_mid]=#ffedeb
theme[temp_end]=#ff95a7

# CPU graph colors (Teal -> Sapphire -> Lavender)
theme[cpu_start]=#ffdb94
theme[cpu_mid]=#f2b2f2
theme[cpu_end]=#ffb8d7

# Mem/Disk free meter (Mauve -> Lavender -> Blue)
theme[free_start]=#ffa6c5
theme[free_mid]=#ffb8d7
theme[free_end]=#fca1d1

# Mem/Disk cached meter (Sapphire -> Blue -> Lavender)
theme[cached_start]=#f2b2f2
theme[cached_mid]=#fca1d1
theme[cached_end]=#ffb8d7

# Mem/Disk available meter (Peach -> Maroon -> Red)
theme[available_start]=#ffbdbc
theme[available_mid]=#f7aab4
theme[available_end]=#ff95a7

# Mem/Disk used meter (Green -> Teal -> Sky)
theme[used_start]=#ffd8c5
theme[used_mid]=#ffdb94
theme[used_end]=#ebd1ff

# Download graph colors (Peach -> Maroon -> Red)
theme[download_start]=#ffbdbc
theme[download_mid]=#f7aab4
theme[download_end]=#ff95a7

# Upload graph colors (Green -> Teal -> Sky)
theme[upload_start]=#ffd8c5
theme[upload_mid]=#ffdb94
theme[upload_end]=#ebd1ff

# Process box color gradient for threads, mem and cpu usage (Sapphire -> Lavender -> Mauve)
theme[process_start]=#f2b2f2
theme[process_mid]=#ffb8d7
theme[process_end]=#ffa6c5
